import image from "../../../assets/DP.png";

const batchParticipantsData = {
  data: [
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID34561",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID34562",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID34563",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID34564",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID34565",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID34566",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID34567",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID34568",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID34569",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345610",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345611",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345612",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345613",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345614",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345615",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345616",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345617",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345618",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345619",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345620",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345621",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345622",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
    {
      studentImage: image,
      studentName: "John Doe",
      studentId: "STDID345623",
      studentCollege: "St Christ College",
      studentMail: "johndoe@email.com",
      studentPhoneNumber: "(555) 555-5555",
      canDelete: true,
    },
  ],
  tableColumns: [
    { key: "studentId", displayName: "Student ID" },
    { key: "studentName", displayName: "Name" },
    { key: "studentCollege", displayName: "College" },
    { key: "studentMail", displayName: "Email ID" },
    { key: "studentPhoneNumber", displayName: "Phone Number" },
  ],
  toggle: true,
  itemsPerPage: 15,
  deleteProps: {
    title: "Confirmation Required",
    message: "Are you sure you want to remove this user?",
    buttonText: "Confirm",
  },
};

export default batchParticipantsData;