const BatchListData = {
  greeting: {
    welcome: "Welcome Back",
    name: "John",
    info: "Here is the information about",
    profile: "Batches",
    showButtons: false,
  },
  dataView: {
    data: [
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "batch",
      },
      {
        miniHeading: "B301",
        mainHeading: "Batch 1",
        Count: 28,
        cardType: "Batch",
      },
    ],
    tableColumns: [
      { key: "miniHeading", displayName: "Batch ID" },
      { key: "mainHeading", displayName: "Batch Name" },
      { key: "Count", displayName: "Count" },
    ],
    toggle: true,
    itemsPerPage: 12,
  },
};

export default BatchListData;
