import image from "../../../assets/DP.png";

const AdminMentorData = {
  greeting: {
    welcome: "Welcome Back",
    name: "John",
    info: "Here is the information about",
    profile: "Mentors",
    showButtons: false,
  },
  data: {
    data: [
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
      {
        studentImage: image,
        studentName: "John Doe",
        studentId: "STDID3456",
        studentCollege: "St Christ College",
        studentMail: "johndoe@email.com",
        studentPhoneNumber: "(555) 555-5555",
        canDelete: false,
      },
    ],
    tableColumns: [
      { key: "studentId", displayName: "Student ID" },
      { key: "studentName", displayName: "Name" },
      { key: "studentCollege", displayName: "College" },
      { key: "studentMail", displayName: "Email ID" },
      { key: "studentPhoneNumber", displayName: "Phone Number" },
    ],
    toggle: true,
    itemsPerPage: 15,
  },
};

export default AdminMentorData;
