const EventDescriptionData = {
    heading: "Exploring Future Technologies",
    text: "Techtalks",
    texts: "Offline",
    desc: "TechTalks 2024 is a full-day event dedicated to exploring emerging technologies and their impact on various industries. Join us for insightful talks, engaging discussions, and networking opportunities with experts in the field.",
    date: "April 10th, 2024",
    time: "10:00 AM - 4:00 PM",
    venue: "Auditorium 101, Engineering Building",
    address: "123 University Ave, Cityville, State, Zip",
    speaker: "Sam Alex, Associate Software Engineer",
    button: "Events",
    buttons: "Exploring Future Technologies",
    small: "edit",
    medium: "delete",
    large: "view participants",
    type: "mentor",
    smaller: "Register",
    addeventprops: {
        defaultValues: {
            eventTitle: "Mock Event Title",
            eventMode: "Online",
            eventType: "Mock Event Type",
            description: "This is a mock description for the event.",
            startDate: "2024-05-24",
            endDate: "2024-05-25",
            startTime: "10:00",
            endTime: "12:00",
            link: "https://mockevent.com",
            speaker: "Mock Speaker",
            organizer: "Mock Organizer",
            location: "wqdwdfrefer",
        },
    },
};

export default EventDescriptionData;
